### ISSUE TITLE
Bug or idk xD

### ISSUE THREAD

**Issue by CaptainMango1** [patrickcerny/typewriterBot#2]
__Traceback (most recent call last):
  File "C:\Users\lukas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\selenium\webdriver\common\service.py", line 72, in start
    self.process = subprocess.Popen(cmd, env=self.env,
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.1264.0_x64__qbz5n2kfra8p0\lib\subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.1264.0_x64__qbz5n2kfra8p0\lib\subprocess.py", line 1420, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] Das System kann die angegebene Datei nicht finden

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\lukas\Downloads\typewriterBot-1.0.1\typewriterbot.py", line 167, in <module>
    driver = Login()
  File "C:\Users\lukas\Downloads\typewriterBot-1.0.1\typewriterbot.py", line 48, in Login
    driver = webdriver.Firefox()
  File "C:\Users\lukas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\selenium\webdriver\firefox\webdriver.py", line 164, in __init__
    self.service.start()
  File "C:\Users\lukas\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\selenium\webdriver\common\service.py", line 81, in start
    raise WebDriverException(
selenium.common.exceptions.WebDriverException: Message: 'geckodriver' executable needs to be i_n PATH._

Thats the error lol idk what to do.

**Comment by patrickcerny** [comment]
Hello!

Well that doesnt look good. This project was more on the fun side than on the serious one, so I dont know if i will ever fix this bug. Looks like the WebDrivers are a) outdated b) buggy.

Maybe try to change them in the drivers folder to their newest version. If that doesnt work, well than I have to look at it myself...

**Comment by CaptainMango1** [comment]
ok. thx for the answer! i will try to fix the drivers!
